language: go

os:
  - linux

go:
  - 1.5
  - 1.6
  - tip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev

script:
  - go vet ./...
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
